//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using MTGO.Common.Entities.Mtgo;

namespace MTGO.Common.Entities.CubeDrafting
{
    public partial class CubeDraftPlayer
    {
        public CubeDraftPlayer()
        {
            this.CubeDraftPicks = new HashSet<CubeDraftPick>();
        }
    
        public virtual int Id { get; set; }
        public virtual bool Confirmed { get; set; }
        public virtual int Team { get; set; }
        public virtual int RequireCollateral { get; set; }
        public virtual bool ProductGiven { get; set; }
        public virtual int Position { get; set; }
        public virtual int DropRound { get; set; }
        public virtual bool DeckBuilt { get; set; }

        public virtual CubeDraft CubeDraft { get; set; }
        public virtual MtgoLink MtgoLink { get; set; }
        public virtual ICollection<CubeDraftPick> CubeDraftPicks { get; set; }
    }
}
