//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Entities.CubeDrafting
{
    public class CubeDraftCard
    {
        public virtual int Id { get; protected set; }
        public virtual int Location { get; set; }

        public virtual CubeDraft CubeDraft { get; set; }
        public virtual Card Card { get; set; }
    }
}
