//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using MTGO.Common.Enums;

namespace MTGO.Common.Entities.CubeDrafting
{
    public class CubeDraft
    {
        public CubeDraft()
        {
            this.CubeDraftCards = new List<CubeDraftCard>();
            this.CubeDraftPlayers = new List<CubeDraftPlayer>();
            this.CubeDraftPicks = new List<CubeDraftPick>();
            this.CubeDraftResults = new List<CubeDraftResult>();
            Created = DateTime.Now;
        }
    
        public virtual int Id { get; protected set; }
        public virtual string Name { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual CubeDraftStatus Status { get; set; }
        public virtual int RoundTime { get; set; }
        public virtual bool RequireWatchers { get; set; }
        public virtual bool Timed { get; set; }
        public virtual string BotName { get; set; }
    
        public virtual User Creator { get; set; }
        public virtual IList<CubeDraftCard> CubeDraftCards { get; protected set; }
        public virtual IList<CubeDraftPlayer> CubeDraftPlayers { get; protected set; }
        public virtual IList<CubeDraftPick> CubeDraftPicks { get; protected set; }
        public virtual IList<CubeDraftResult> CubeDraftResults { get; protected set; }
    }
}
