//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using MTGO.Common.Enums;

namespace MTGO.Common.Entities
{
    public class Ban
    {
        public virtual int Id { get; protected set; }
        public virtual string IpAddress { get; set; }
        public virtual BanType? BanType { get; set; }
        public virtual DateTime Expires { get; set; }
        public virtual string Reason { get; set; }

        public virtual User User { get; set; }
    }
}
