//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Entities
{
    public class Broadcaster
    {
        public virtual int Id { get; protected set; }
        public virtual string IrcSettings { get; set; }
        public virtual User User { get; set; }
    }
}
