//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace MTGO.Common.Entities
{
    public partial class Donation
    {
        public Donation()
        {
            this.Amount = 0D;
        }
    
        public virtual int Id { get; protected set; }
        public virtual string TxnId { get; set; }
        public virtual string Email { get; set; }
        public virtual string Username { get; set; }
        public virtual double Amount { get; set; }
        public virtual DateTime DateTime { get; set; }
    }
}
