//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MTGO.Common.Enums;
using System.Collections.Generic;

namespace MTGO.Common.Entities
{
    public partial class DraftPick
    {
        public virtual int Id { get; protected set; }
        public virtual int DraftId { get; set; }
        public virtual int Pick { get; set; }
        public virtual int Pack { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual int Time { get; set; }
        public virtual Card PickCard { get; set; }

        public virtual Draft Draft { get; protected set; }
        public virtual IList<Card> Picks { get; protected set; }
    }
}
