//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGBotWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string MagicCardsInfoId { get; set; }
        public bool Foil { get; set; }
        public Nullable<int> CardSetId { get; set; }
        public string Rarity { get; set; }
    
        public virtual CardSet CardSet { get; set; }
    }
}
