//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDbContext : DbContext
    {
        public MainDbContext()
            : base("name=MainDbContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Broadcaster> Broadcasters { get; set; }
        public DbSet<Card> Cards { get; set; }
        public DbSet<CardSet> CardSets { get; set; }
        public DbSet<DraftPick> DraftPicks { get; set; }
        public DbSet<Draft> Drafts { get; set; }
        public DbSet<Donation> Donations { get; set; }
        public DbSet<Vote> Votes { get; set; }
        public DbSet<TwitchOAuth> TwitchOAuths { get; set; }
        public DbSet<CubeDraftCard> CubeDraftCards { get; set; }
        public DbSet<CubeDraftPick> CubeDraftPicks { get; set; }
        public DbSet<CubeDraftPlayer> CubeDraftPlayers { get; set; }
        public DbSet<CubeDraft> CubeDrafts { get; set; }
        public DbSet<NCard> NCards { get; set; }
        public DbSet<NSet> NSets { get; set; }
        public DbSet<CubeDraftResult> CubeDraftResults { get; set; }
        public DbSet<Ban> Bans { get; set; }
        public DbSet<MtgoLink> MtgoLink { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
