//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CubeDraftResult
    {
        public int Id { get; set; }
        public int DraftId { get; set; }
        public int Round { get; set; }
        public int Player1Id { get; set; }
        public Nullable<int> Player2Id { get; set; }
        public int Player1Wins { get; set; }
        public int Player2Wins { get; set; }
        public int Ties { get; set; }
        public int CurrentGame { get; set; }
    
        public virtual CubeDraftPlayer CubeDraftPlayer1 { get; set; }
        public virtual CubeDraftPlayer CubeDraftPlayer2 { get; set; }
    }
}
