//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CubeDraft
    {
        public CubeDraft()
        {
            this.CubeDraftCards = new HashSet<CubeDraftCard>();
            this.CubeDraftPlayers = new HashSet<CubeDraftPlayer>();
            this.CubeDraftPicks = new HashSet<CubeDraftPick>();
            this.CubeDraftResults = new HashSet<CubeDraftResult>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
        public int BroadcasterId { get; set; }
        public CubeDraftStatus Status { get; set; }
        public int RoundTime { get; set; }
        public bool RequireWatchers { get; set; }
        public bool Timed { get; set; }
        public string BotName { get; set; }
    
        public virtual Broadcaster Broadcaster { get; set; }
        public virtual ICollection<CubeDraftCard> CubeDraftCards { get; set; }
        public virtual ICollection<CubeDraftPlayer> CubeDraftPlayers { get; set; }
        public virtual ICollection<CubeDraftPick> CubeDraftPicks { get; set; }
        public virtual ICollection<CubeDraftResult> CubeDraftResults { get; set; }
    }
}
