//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CubeDraftPick
    {
        public int Id { get; set; }
        public int CubedraftId { get; set; }
        public int PlayerId { get; set; }
        public string Picks { get; set; }
        public int Pick { get; set; }
        public Nullable<int> PickId { get; set; }
    }
}
