//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CubeDraftPlayer
    {
        public CubeDraftPlayer()
        {
            this.CubeDraftPicks = new HashSet<CubeDraftPick>();
        }
    
        public int Id { get; set; }
        public int CubedraftId { get; set; }
        public int MtgoLinkId { get; set; }
        public bool Confirmed { get; set; }
        public int Team { get; set; }
        public int RequireCollateral { get; set; }
        public bool ProductGiven { get; set; }
        public int Position { get; set; }
        public int DropRound { get; set; }
        public bool DeckBuilt { get; set; }
    
        public virtual ICollection<CubeDraftPick> CubeDraftPicks { get; set; }
        public virtual MtgoLink MtgoLink { get; set; }
    }
}
