//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Models
{
    using System;
    
    public enum CubeDraftStatus : int
    {
        Init = 0,
        PreStart = 1,
        Drafting = 2,
        ProductHandOut = 3,
        InMatches = 4,
        ProductHandIn = 5,
        Exception = 6,
        Completed = 7
    }
}
