//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draft
    {
        public Draft()
        {
            this.CurrentPack = 0;
            this.DraftPicks = new HashSet<DraftPick>();
        }
    
        public int Id { get; set; }
        public int DraftId { get; set; }
        public int TournamentId { get; set; }
        public int BroadcasterId { get; set; }
        public string Players { get; set; }
        public string FinalDeck { get; set; }
        public Nullable<DraftStatus> DraftStatus { get; set; }
        public int CurrentPack { get; set; }
    
        public virtual Broadcaster Broadcaster { get; set; }
        public virtual ICollection<DraftPick> DraftPicks { get; set; }
    }
}
