//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCard
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Set { get; set; }
        public string Type { get; set; }
        public string Rarity { get; set; }
        public string Manacost { get; set; }
        public string ConvertedManacost { get; set; }
        public string Power { get; set; }
        public string Toughness { get; set; }
        public Nullable<sbyte> Loyalty { get; set; }
        public string Ability { get; set; }
        public string Flavor { get; set; }
        public Nullable<sbyte> Variation { get; set; }
        public string Artist { get; set; }
        public string Number { get; set; }
        public string Rating { get; set; }
        public string Ruling { get; set; }
        public string Color { get; set; }
        public string GeneratedMana { get; set; }
        public Nullable<double> pricing_low { get; set; }
        public Nullable<double> pricing_mid { get; set; }
        public Nullable<double> pricing_high { get; set; }
        public string back_id { get; set; }
        public string watermark { get; set; }
        public string name_CN { get; set; }
        public string name_TW { get; set; }
        public string name_FR { get; set; }
        public string name_DE { get; set; }
        public string name_IT { get; set; }
        public string name_JP { get; set; }
        public string name_PT { get; set; }
        public string name_RU { get; set; }
        public string name_ES { get; set; }
        public string name_KO { get; set; }
        public string legality_Block { get; set; }
        public string legality_Standard { get; set; }
        public string legality_Extended { get; set; }
        public string legality_Modern { get; set; }
        public string legality_Legacy { get; set; }
        public string legality_Vintage { get; set; }
        public string legality_Highlander { get; set; }
        public string legality_French_Commander { get; set; }
        public string legality_Commander { get; set; }
        public string legality_Peasant { get; set; }
        public string legality_Pauper { get; set; }
    
        public virtual NSet NSet { get; set; }
    }
}
