//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGO.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSet
    {
        public string Name { get; set; }
        public string Code { get; set; }
        public string CodeMagiccards { get; set; }
        public string Date { get; set; }
        public string IsPromo { get; set; }
    }
}
