//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTGBotWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public Donation()
        {
            this.Amount = 0D;
        }
    
        public int Id { get; set; }
        public string TxnId { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public double Amount { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
